-- REGIONES
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (1, 'reg_001', 'Region de Arica y Parinacota', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (2, 'reg_002', 'Region de Tarapaca', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (3, 'reg_003', 'Region de Antofagasta', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (4, 'reg_004', 'Region de Atacama', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (5, 'reg_005', 'Region de Coquimbo', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (6, 'reg_006', 'Region de Valparaiso', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (7, 'reg_007', 'Region Metropolitana de Santiago', 1990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (8, 'reg_008', 'Region del Libertador General Bernardo Ohiggins', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (9, 'reg_009', 'Region del Maule', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (10, 'reg_010', 'Region de Nuble', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (11, 'reg_011', 'Region del Biobio', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (12, 'reg_012', 'Region de la Araucania', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (13, 'reg_013', 'Region de los Rios', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (14, 'reg_014', 'Region de los Lagos', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (15, 'reg_015', 'Region de Aysen del General Carlos Ibanez del Campo', 6990);
INSERT INTO region(region_id, code, region, shipping_cost) VALUES (16, 'reg_016', 'Region de Magallanes y de la Antartica Chilena', 6990);

-- COMUNAS
-- Región de Arica y Parinacota (region_id = 1)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (1, 'com_001', 'Arica', 1);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (2, 'com_002', 'Camarones', 1);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (3, 'com_003', 'Putre', 1);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (4, 'com_004', 'General Lagos', 1);

-- Región de Tarapacá (region_id = 2)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (5, 'com_005', 'Iquique', 2);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (6, 'com_006', 'Alto Hospicio', 2);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (7, 'com_007', 'Pozo Almonte', 2);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (8, 'com_008', 'Camina', 2);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (9, 'com_009', 'Colchane', 2);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (10, 'com_010', 'Huara', 2);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (11, 'com_011', 'Pica', 2);

-- Región de Antofagasta (region_id = 3)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (12, 'com_012', 'Antofagasta', 3);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (13, 'com_013', 'Mejillones', 3);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (14, 'com_014', 'Sierra Gorda', 3);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (15, 'com_015', 'Taltal', 3);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (16, 'com_016', 'Calama', 3);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (17, 'com_017', 'Ollague', 3);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (18, 'com_018', 'San Pedro de Atacama', 3);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (19, 'com_019', 'Tocopilla', 3);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (20, 'com_020', 'Maria Elena', 3);

-- Región de Atacama (region_id = 4)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (21, 'com_021', 'Copiapo', 4);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (22, 'com_022', 'Caldera', 4);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (23, 'com_023', 'Tierra Amarilla', 4);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (24, 'com_024', 'Chanaral', 4);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (25, 'com_025', 'Diego de Almagro', 4);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (26, 'com_026', 'Vallenar', 4);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (27, 'com_027', 'Alto del Carmen', 4);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (28, 'com_028', 'Freirina', 4);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (29, 'com_029', 'Huasco', 4);

-- Región de Coquimbo (region_id = 5)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (30, 'com_030', 'La Serena', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (31, 'com_031', 'Coquimbo', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (32, 'com_032', 'Andacollo', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (33, 'com_033', 'La Higuera', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (34, 'com_034', 'Paihuano', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (35, 'com_035', 'Vicuna', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (36, 'com_036', 'Illapel', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (37, 'com_037', 'Canela', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (38, 'com_038', 'Los Vilos', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (39, 'com_039', 'Salamanca', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (40, 'com_040', 'Ovalle', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (41, 'com_041', 'Combarbala', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (42, 'com_042', 'Monte Patria', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (43, 'com_043', 'Punitaqui', 5);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (44, 'com_044', 'Rio Hurtado', 5);

-- Región de Valparaíso (region_id = 6)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (45, 'com_045', 'Valparaiso', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (46, 'com_046', 'Casablanca', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (47, 'com_047', 'Concon', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (48, 'com_048', 'Juan Fernandez', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (49, 'com_049', 'Puchuncavi', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (50, 'com_050', 'Quintero', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (51, 'com_051', 'Vina del Mar', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (52, 'com_052', 'Isla de Pascua', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (53, 'com_053', 'Los Andes', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (54, 'com_054', 'Calle Larga', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (55, 'com_055', 'Rinconada', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (56, 'com_056', 'San Esteban', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (57, 'com_057', 'La Ligua', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (58, 'com_058', 'Cabildo', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (59, 'com_059', 'Papudo', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (60, 'com_060', 'Petorca', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (61, 'com_061', 'Zapallar', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (62, 'com_062', 'Quillota', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (63, 'com_063', 'Calera', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (64, 'com_064', 'Hijuelas', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (65, 'com_065', 'La Cruz', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (66, 'com_066', 'Nogales', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (67, 'com_067', 'San Antonio', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (68, 'com_068', 'Algarrobo', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (69, 'com_069', 'Cartagena', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (70, 'com_070', 'El Quisco', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (71, 'com_071', 'El Tabo', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (72, 'com_072', 'Santo Domingo', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (73, 'com_073', 'San Felipe', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (74, 'com_074', 'Catemu', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (75, 'com_075', 'Llaillay', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (76, 'com_076', 'Panquehue', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (77, 'com_077', 'Putaendo', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (78, 'com_078', 'Santa Maria', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (79, 'com_079', 'Quilpue', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (80, 'com_080', 'Limache', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (81, 'com_081', 'Olmue', 6);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (82, 'com_082', 'Villa Alemana', 6);

-- Región Metropolitana de Santiago (region_id = 7)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (83, 'com_083', 'Cerrillos', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (84, 'com_084', 'Cerro Navia', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (85, 'com_085', 'Conchali', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (86, 'com_086', 'El Bosque', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (87, 'com_087', 'Estacion Central', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (88, 'com_088', 'Huechuraba', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (89, 'com_089', 'Independencia', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (90, 'com_090', 'La Cisterna', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (91, 'com_091', 'La Florida', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (92, 'com_092', 'La Granja', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (93, 'com_093', 'La Pintana', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (94, 'com_094', 'La Reina', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (95, 'com_095', 'Las Condes', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (96, 'com_096', 'Lo Barnechea', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (97, 'com_097', 'Lo Espejo', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (98, 'com_098', 'Lo Prado', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (99, 'com_099', 'Macul', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (100, 'com_100', 'Maipu', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (101, 'com_101', 'Nunoa', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (102, 'com_102', 'Pedro Aguirre Cerda', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (103, 'com_103', 'Penalolen', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (104, 'com_104', 'Providencia', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (105, 'com_105', 'Pudahuel', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (106, 'com_106', 'Quilicura', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (107, 'com_107', 'Quinta Normal', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (108, 'com_108', 'Recoleta', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (109, 'com_109', 'Renca', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (110, 'com_110', 'San Joaquin', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (111, 'com_111', 'San Miguel', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (112, 'com_112', 'San Ramon', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (113, 'com_113', 'Santiago', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (114, 'com_114', 'Vitacura', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (115, 'com_115', 'Puente Alto', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (116, 'com_116', 'Pirque', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (117, 'com_117', 'San Jose de Maipo', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (118, 'com_118', 'Colina', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (119, 'com_119', 'Lampa', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (120, 'com_120', 'Tiltil', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (121, 'com_121', 'San Bernardo', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (122, 'com_122', 'Buin', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (123, 'com_123', 'Calera de Tango', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (124, 'com_124', 'Paine', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (125, 'com_125', 'Melipilla', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (126, 'com_126', 'Alhue', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (127, 'com_127', 'Curacavi', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (128, 'com_128', 'Maria Pinto', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (129, 'com_129', 'San Pedro', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (130, 'com_130', 'Talagante', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (131, 'com_131', 'El Monte', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (132, 'com_132', 'Isla de Maipo', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (133, 'com_133', 'Padre Hurtado', 7);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (134, 'com_134', 'Penaflor', 7);

-- Región del Libertador General Bernardo O'Higgins (region_id = 8)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (135, 'com_135', 'Rancagua', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (136, 'com_136', 'Codegua', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (137, 'com_137', 'Coinco', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (138, 'com_138', 'Coltauco', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (139, 'com_139', 'Donihue', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (140, 'com_140', 'Graneros', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (141, 'com_141', 'Las Cabras', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (142, 'com_142', 'Machali', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (143, 'com_143', 'Malloa', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (144, 'com_144', 'Mostazal', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (145, 'com_145', 'Olivar', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (146, 'com_146', 'Peumo', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (147, 'com_147', 'Pichidegua', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (148, 'com_148', 'Quinta de Tilcoco', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (149, 'com_149', 'Rengo', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (150, 'com_150', 'Requinoa', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (151, 'com_151', 'San Vicente', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (152, 'com_152', 'Pichilemu', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (153, 'com_153', 'La Estrella', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (154, 'com_154', 'Litueche', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (155, 'com_155', 'Marchihue', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (156, 'com_156', 'Navidad', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (157, 'com_157', 'Paredones', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (158, 'com_158', 'San Fernando', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (159, 'com_159', 'Chepica', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (160, 'com_160', 'Chimbarongo', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (161, 'com_161', 'Lolol', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (162, 'com_162', 'Nancagua', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (163, 'com_163', 'Palmilla', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (164, 'com_164', 'Peralillo', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (165, 'com_165', 'Placilla', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (166, 'com_166', 'Pumanque', 8);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (167, 'com_167', 'Santa Cruz', 8);

-- Región del Maule (region_id = 9)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (168, 'com_168', 'Talca', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (169, 'com_169', 'Constitucion', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (170, 'com_170', 'Curepto', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (171, 'com_171', 'Empedrado', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (172, 'com_172', 'Maule', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (173, 'com_173', 'Pelarco', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (174, 'com_174', 'Pencahue', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (175, 'com_175', 'Rio Claro', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (176, 'com_176', 'San Clemente', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (177, 'com_177', 'San Rafael', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (178, 'com_178', 'Cauquenes', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (179, 'com_179', 'Chanco', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (180, 'com_180', 'Pelluhue', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (181, 'com_181', 'Curico', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (182, 'com_182', 'Hualane', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (183, 'com_183', 'Licanten', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (184, 'com_184', 'Molina', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (185, 'com_185', 'Rauco', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (186, 'com_186', 'Romeral', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (187, 'com_187', 'Sagrada Familia', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (188, 'com_188', 'Teno', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (189, 'com_189', 'Vichuquen', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (190, 'com_190', 'Linares', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (191, 'com_191', 'Colbun', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (192, 'com_192', 'Longavi', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (193, 'com_193', 'Parral', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (194, 'com_194', 'Retiro', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (195, 'com_195', 'San Javier', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (196, 'com_196', 'Villa Alegre', 9);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (197, 'com_197', 'Yerbas Buenas', 9);

-- Región de Ñuble (region_id = 10)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (198, 'com_198', 'Cobquecura', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (199, 'com_199', 'Coelemu', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (200, 'com_200', 'Ninhue', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (201, 'com_201', 'Portezuelo', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (202, 'com_202', 'Quirihue', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (203, 'com_203', 'Ranquil', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (204, 'com_204', 'Treguaco', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (205, 'com_205', 'Bulnes', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (206, 'com_206', 'Chillan Viejo', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (207, 'com_207', 'Chillan', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (208, 'com_208', 'El Carmen', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (209, 'com_209', 'Pemuco', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (210, 'com_210', 'Pinto', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (211, 'com_211', 'Quillon', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (212, 'com_212', 'San Ignacio', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (213, 'com_213', 'Yungay', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (214, 'com_214', 'Coihueco', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (215, 'com_215', 'Niquen', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (216, 'com_216', 'San Carlos', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (217, 'com_217', 'San Fabian', 10);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (218, 'com_218', 'San Nicolas', 10);

-- Región del Biobío (region_id = 11)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (219, 'com_219', 'Concepcion', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (220, 'com_220', 'Coronel', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (221, 'com_221', 'Chiguayante', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (222, 'com_222', 'Florida', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (223, 'com_223', 'Hualqui', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (224, 'com_224', 'Lota', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (225, 'com_225', 'Penco', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (226, 'com_226', 'San Pedro de la Paz', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (227, 'com_227', 'Santa Juana', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (228, 'com_228', 'Talcahuano', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (229, 'com_229', 'Tome', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (230, 'com_230', 'Hualpen', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (231, 'com_231', 'Lebu', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (232, 'com_232', 'Arauco', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (233, 'com_233', 'Canete', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (234, 'com_234', 'Contulmo', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (235, 'com_235', 'Curanilahue', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (236, 'com_236', 'Los Alamos', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (237, 'com_237', 'Tirua', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (238, 'com_238', 'Los Angeles', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (239, 'com_239', 'Antuco', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (240, 'com_240', 'Cabrero', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (241, 'com_241', 'Laja', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (242, 'com_242', 'Mulchen', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (243, 'com_243', 'Nacimiento', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (244, 'com_244', 'Negrete', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (245, 'com_245', 'Quilaco', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (246, 'com_246', 'Quilleco', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (247, 'com_247', 'San Rosendo', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (248, 'com_248', 'Santa Barbara', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (249, 'com_249', 'Tucapel', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (250, 'com_250', 'Yumbel', 11);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (251, 'com_251', 'Alto Biobio', 11);

-- Región de La Araucanía (region_id = 12)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (252, 'com_252', 'Temuco', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (253, 'com_253', 'Carahue', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (254, 'com_254', 'Cunco', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (255, 'com_255', 'Curarrehue', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (256, 'com_256', 'Freire', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (257, 'com_257', 'Galvarino', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (258, 'com_258', 'Gorbea', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (259, 'com_259', 'Lautaro', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (260, 'com_260', 'Loncoche', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (261, 'com_261', 'Melipeuco', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (262, 'com_262', 'Nueva Imperial', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (263, 'com_263', 'Padre las Casas', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (264, 'com_264', 'Perquenco', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (265, 'com_265', 'Pitrufquen', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (266, 'com_266', 'Pucon', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (267, 'com_267', 'Saavedra', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (268, 'com_268', 'Teodoro Schmidt', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (269, 'com_269', 'Tolten', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (270, 'com_270', 'Vilcun', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (271, 'com_271', 'Villarrica', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (272, 'com_272', 'Cholchol', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (273, 'com_273', 'Angol', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (274, 'com_274', 'Collipulli', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (275, 'com_275', 'Curacautin', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (276, 'com_276', 'Ercilla', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (277, 'com_277', 'Lonquimay', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (278, 'com_278', 'Los Sauces', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (279, 'com_279', 'Lumaco', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (280, 'com_280', 'Puren', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (281, 'com_281', 'Renaico', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (282, 'com_282', 'Traiguen', 12);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (283, 'com_283', 'Victoria', 12);

-- Región de Los Ríos (region_id = 13)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (284, 'com_284', 'Valdivia', 13);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (285, 'com_285', 'Corral', 13);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (286, 'com_286', 'Lanco', 13);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (287, 'com_287', 'Los Lagos', 13);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (288, 'com_288', 'Mafil', 13);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (289, 'com_289', 'Mariquina', 13);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (290, 'com_290', 'Paillaco', 13);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (291, 'com_291', 'Panguipulli', 13);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (292, 'com_292', 'La Union', 13);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (293, 'com_293', 'Futrono', 13);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (294, 'com_294', 'Lago Ranco', 13);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (295, 'com_295', 'Rio Bueno', 13);

-- Región de Los Lagos (region_id = 14)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (296, 'com_296', 'Puerto Montt', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (297, 'com_297', 'Calbuco', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (298, 'com_298', 'Cochamo', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (299, 'com_299', 'Fresia', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (300, 'com_300', 'Frutillar', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (301, 'com_301', 'Los Muermos', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (302, 'com_302', 'Llanquihue', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (303, 'com_303', 'Maullin', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (304, 'com_304', 'Puerto Varas', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (305, 'com_305', 'Castro', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (306, 'com_306', 'Ancud', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (307, 'com_307', 'Chonchi', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (308, 'com_308', 'Curaco de Velez', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (309, 'com_309', 'Dalcahue', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (310, 'com_310', 'Puqueldon', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (311, 'com_311', 'Queilen', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (312, 'com_312', 'Quellon', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (313, 'com_313', 'Quemchi', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (314, 'com_314', 'Quinchao', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (315, 'com_315', 'Osorno', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (316, 'com_316', 'Puerto Octay', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (317, 'com_317', 'Purranque', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (318, 'com_318', 'Puyehue', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (319, 'com_319', 'Rio Negro', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (320, 'com_320', 'San Juan de la Costa', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (321, 'com_321', 'San Pablo', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (322, 'com_322', 'Chaiten', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (323, 'com_323', 'Futaleufu', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (324, 'com_324', 'Hualaihue', 14);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (325, 'com_325', 'Palena', 14);

-- Región de Aysén del General Carlos Ibáñez del Campo (region_id = 15)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (326, 'com_326', 'Coyhaique', 15);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (327, 'com_327', 'Lago Verde', 15);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (328, 'com_328', 'Aysen', 15);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (329, 'com_329', 'Cisnes', 15);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (330, 'com_330', 'Guaitecas', 15);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (331, 'com_331', 'Cochrane', 15);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (332, 'com_332', 'Ohiggins', 15);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (333, 'com_333', 'Tortel', 15);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (334, 'com_334', 'Chile Chico', 15);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (335, 'com_335', 'Rio Ibanez', 15);

-- Región de Magallanes y de la Antártica Chilena (region_id = 16)
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (336, 'com_336', 'Punta Arenas', 16);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (337, 'com_337', 'Laguna Blanca', 16);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (338, 'com_338', 'Rio Verde', 16);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (339, 'com_339', 'San Gregorio', 16);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (340, 'com_340', 'Cabo de Hornos', 16);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (341, 'com_341', 'Antartica', 16);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (342, 'com_342', 'Porvenir', 16);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (343, 'com_343', 'Primavera', 16);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (344, 'com_344', 'Timaukel', 16);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (345, 'com_345', 'Natales', 16);
INSERT INTO commune(commune_id, code, commune, region_id) VALUES (346, 'com_346', 'Torres del Paine', 16);